### PR TITLE
Use .data() instead of &vector[0]

### PR DESCRIPTION
**Pull request by aledomu**
Is there any problem with updating the submodules to an untagged commit?

- - -
This change is [Reviewable](https://reviewable.io/reviews/highperformancecoder/ecolab/13)

### CODE REVIEW

**Comment by highperformancecoder** [comment]
On Thu, Mar 23, 2023 at 07:44:40PM -0700, Alejandro Domínguez wrote:
> Is there any problem with updating the submodules to an untagged commit?

No - I do that all the time.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by aledomu** [comment]
The CI tests are failing in the same way even when reverting the changes in this PR. Merge anyway?

**Comment by highperformancecoder** [comment]
Yes - it is broken in master, so not your problem. Most likely, it is a change in dependent libraries, but I'll check later today after rebuilding the CI docker image, which I need to do for Minsky.

**Comment by highperformancecoder** [comment]
Been so busy trying to fix the broken CI test on Minsky, that I haven
't been able to get to this.

But your code is not the problem, so I may as well merge.

**Pull request merged**
